runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.75
  target_concurrent_requests: 100

resources:
  cpu: 0.75
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:15Pxc+9xshjdTGMcSLQc+Z6XWU4sQ3ekAfH+3PsiCHA=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: file
  SESSION_DRIVER: file

runtime_config:
  document_root: public
